services: 
  postgres:
    image: postgres:latest
    container_name: postgres_bd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@AthusOtto@0401@@"
      POSTGRES_DB: my_backend_app
    ports:
      - "5432:5432"
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  backend:
    build: ./backend
    container_name: backend_app
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: my_backend_app
      DB_USER: postgres
      DB_PASS: "@AthusOtto@0401@@"
      JWT_SECRET: supersegredo
      # MOODLE_BASE_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    container_name: mariadb_moodle
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - backend
  moodle:
    image: docker.io/bitnami/moodle:5.0
    container_name: moodle_app
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=user
      - MOODLE_PASSWORD=bitnami
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    networks:
      - backend  

volumes:
  postgres_data:
  mariadb_data:
  moodle_data:
  moodledata_data:

networks:
  backend:
    driver: bridge

# acessar o banco =>  docker exec -it postgres_bd psql -U postgres -d my_backend_app
# migrar o banco =>  docker exec -it backend_app npx sequelize-cli db:migrate
# acessar o moodle_bd => docker exec -it mariadb_moodle mysql -u bn_moodle bitnami_moodle
